import type { Metadata } from "next";
import { Inter, Playfair_Display, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav";
import Image from "next/image";

const body = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const display = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
});

const code = JetBrains_Mono({
  variable: "--font-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${body.variable} ${display.variable} ${code.variable} antialiased`}>
        <div className="min-h-screen bg-background">
          <div className="mx-auto max-w-6xl px-6 py-16 flex flex-col gap-6 relative">
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
